### ISSUE TITLE
Is it possible to prevent the Client from automatically bringing the application in foreground ?

### ISSUE THREAD

**Issue by teisseire117** [nomi-san/league-loader#12]
I've tried looking over the .js code to see if something was getting my attention but there's a lot more code than I expected and I can't really find what I'm looking for.

I'm looking for the code that's responsible for bring the application in the foreground when we have to accept queue. Because I made a plug-in to automatically accept it (I posted it here https://github.com/nomi-san/league-loader/issues/4#issuecomment-1399453857) but if the applications pops up then it makes it not really useful.

If anyone has ideas

**Comment by nomi-san** [comment]
You can try this API:

```http
POST /riotclient/ux-allow-foreground
```

I don't know how can it do and its request body. But here is the hint.

```json
"PostRiotclientUxAllowForeground": "Allows the background process to launch the game into the foregound.",
"PostRiotclientUxFlash": "Flash the ux process' main window and the taskbar/dock icon, if they exist."
```

> Flashing the Ux always appears when receive chat message or change runes during champ-select.

**Comment by teisseire117** [comment]
> You can try this API:
> 
> ```httpspec
> POST /riotclient/ux-allow-foreground
> ```
> 
> I don't know how can it do and its request body. But here is the hint.
> 
> ```json
> "PostRiotclientUxAllowForeground": "Allows the background process to launch the game into the foregound.",
> "PostRiotclientUxFlash": "Flash the ux process' main window and the taskbar/dock icon, if they exist."
> ```
> 
> > Flashing the Ux always appears when receive chat message or change runes during champ-select.

I searched a bit and apparently these endpoint don't expect a body, they are simply used to bring the app in the foreground and flash the app's icon.

The name `ux-allow-foreground` is misleading as itsn't used to "allow" or not the app to be bring in Foreground. It's used to bring the app in the Foreground and nothing else.

I'm looking at a tutorial on memory dumping, and I'm trying to do it on every league*.exe I find, because I suspect this endpoint is called in one of them. I'll notify you if I find anything :)

**Comment by nomi-san** [comment]
> I'm looking at a tutorial on memory dumping, and I'm trying to do it on every league*.exe I find, because I suspect this endpoint is called in one of them. I'll notify you if I find anything :)

You can put these EXEs into Dependencies Walker or monitor them with API Monitor to get OS APIs are used.
There are many win32 functions able to achieve the same behaviours.

```cpp
ShowWindow();
SetWindowPos();
BringWindowToTop();
SetForegroundWindow();
SetActiveWindow();
```
