### ISSUE TITLE
Can you make it so we have the Riot client API port/auth-token in global variables or similar ?

### ISSUE THREAD

**Issue by teisseire117** [nomi-san/league-loader#13]
Hello again !

In ranked champ select the player names are hidden. I want to make a plug-in that unhides them. I found that it's possible to retrieve the real usernames by using the Riot client API, which is different to the LCU, with different endpoints.  (The interesting one being `/chat/v5/participants/champ-select`)

It uses a different port, and use an auth-token, which changes everytime the client starts up.

On Window you can retrieve the port by using in a terminal the command : `wmic PROCESS WHERE name='LeagueClientUx.exe' GET commandline`

In Mac OS you can do : `ps -A | grep LeagueClientUx`

I searched a little bit, and apparently it's not possible to do these commands in javascript without nodejs.
So I was wondering, I'm not sure exactly how league-loader works, but I very much suppose there's some sort of "pre-load" that uses C/C++ or another low-level language, which could be used to retrieve the Riot client API/auth-token, and made them available in global variables in the DevTools

I put a red arrow on the two informations here : 
![62M6f2S](https://user-images.githubusercontent.com/43145883/213944274-03215149-3cfd-4580-9593-808dc46450f4.png)

**Comment by nomi-san** [comment]
It's quite easy. Just use this API:
```http
GET /riotclient/command-line-args
```

The response is the command line of LeagueClient.exe.
You have to parse them to get auth token and password.

// up-to-date APIs: http://www.mingweisamuel.com/lcu-schema/tool/#/

**Comment by teisseire117** [comment]
> ```httpspec
> /riotclient/command-line-args
> ```

Once again, thank you, you're spot on everytime

**Comment by nomi-san** [comment]
Riot Client APIs have response header with origin diff to LCU port, so any request will fail due to CORS.
You can bypass them by disabling CEF web security in [INSECURE_OPTIONS](https://github.com/nomi-san/league-loader/blob/main/INSECURE_OPTIONS.md).

Next update I'll add something magical to the network layer to bypass them.
