### ISSUE TITLE
Request: Plugins folder opener button

### ISSUE THREAD

**Issue by Roydevil** [nomi-san/league-loader#16]
Can you create a button that open plugins folder
It's inconvenient to find that every time 🐧

**Comment by nomi-san** [comment]
- [ ] Native JS function to open plugins folder
- [ ] Opener button in settings panel (for `league-loader.js` plugin)

```js
function openPluginsFolder() {
  native OpenPluginsFolder();
  OpenPluginsFolder();
}
```

**Comment by Roydevil** [comment]
> ```js
> function openPluginsFolder() {
>   native OpenPluginsFolder();
>   OpenPluginsFolder();
> }
> ```

How can I using it

**Comment by nomi-san** [comment]
I added tasks to do them for next release.
Native functions must be implemented in v8 extension.

https://github.com/nomi-san/league-loader/blob/30b7cce27d71b5e14a97f0b0926a6f802107cffe/d3d9/src/ext_code.h#L16-L19
