### ISSUE TITLE
Is it possible to access the iFrames ?

### ISSUE THREAD

**Issue by teisseire117** [nomi-san/league-loader#20]
Hey,

I'm trying to make a theme for the client but I'm facing a difficulty trying to modify the TFT page. The page is in an iframe and its src is https://prod.embed.rgpub.io/wwpub-lunar-gala-2023/en_US/ , I found out it's not possible to modify the elements' style that are inside an Iframe if its src is different that the current origin.

It returns : VM9420:1 Uncaught DOMException: Blocked a frame with origin "https://127.0.0.1:28773" from accessing a cross-origin frame.
    at <anonymous>:1:73
    
 I modified the config.cfg file in the league-loader folder to : 
 ```
 [Main]
LeaguePath=C:\Riot Games\League of Legends
DisableWebSecurity=1
IgnoreCertificateErrors=1
```

But same error. If anyone knows a work-around that would be helpful ! There are a lot of iframes used in the client

**Comment by nomi-san** [comment]
Disabling web security also disable all same site and cross-origin policies.
I have not tested with iframe, but seems there is no possible solution since Chromium v91.

**Comment by teisseire117** [comment]
> Disabling web security also disable all same site and cross-origin policies. I have not tested with iframe, but seems there is no possible solution since Chromium v91.

I see, thank you anyway
