### ISSUE TITLE
League of legends China server LCU

### ISSUE THREAD

**Issue by 871766329** [nomi-san/league-loader#3]
At this stage, the Chinese servers of the League of Heroes cannot use the LCU API，Is there a solution，please

**Comment by nomi-san** [comment]
> At this stage

Is it Worlds 2022?

I cannot test on this server, so I don't know what's going on.
Can you describe this issue in detail?

**Comment by 871766329** [comment]
从2022-9-26起  The lcu api of the League of Heroes client prohibits third-party plug-ins from calling its api

**Comment by nomi-san** [comment]
> 从2022-9-26起 The lcu api of the League of Heroes client

Wait.. what is League of Heroes client?
I never heard about it even though searched on Baidu.

![image](https://user-images.githubusercontent.com/38210249/195988739-fb088711-07c6-4d04-a3a0-272e0232e655.png)

**Comment by 871766329** [comment]
League of Heroes client is a Chinese league of legends client

**Comment by nomi-san** [comment]
> I can provide you with QQ.

Let's email me your referral code or just a WeGame account.

**Comment by 871766329** [comment]
What social platform do you use? I can add your friend and send you a wegame account.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Valentin ***@***.***&gt;; 
发送时间: 2022年10月20日(星期四) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nomi-san/league-loader] League of legends China server LCU (Issue #3)





  
I can provide you with QQ.
  
Let's email me your referral code or just a WeGame account.
