### ISSUE TITLE
Folder Support within Plugins

### ISSUE THREAD

**Issue by 909oce** [nomi-san/league-loader#34]
Hi, to make things easier for the user when using other peoples plugins, could you add support for loading JS within a folder within plugins.

For example, I want to put all my JS files in a folder named 909 within plugins (//plugins/909/example.js).

This way its easier to install and use multiple different plugins without them all being cluttered.

End goal is for me to keep all assets and JS, CSS files, etc in the 909 plugin so its just drag and drop single folder to install

**Comment by nomi-san** [comment]
Already planned for next update.

`index.js` in subfolder (aka plugin's entry point) will be executed.

```elm
plugins/
  |__sub-folder/
     |__index.js             <-- entry
     |__[other resources]
     ...
  |__top-level.js
  ...
```

So, how to access its resources?

We already had `//assets/` to access resources from **assets** folder.
The fastest way is to do a similar one, `//plugins/`.

```html
<img src="//plugins/sub-folder/your-image.png" alt="" />
```

<br>

**Comment by 909oce** [comment]
sounds good. how would i run js files within a subfolder. do they still auto execute unless starts with _ ?

**Comment by nomi-san** [comment]
Only top-level files and index.js inside top-level folder will be executed.
Except folder and file name start with underscore or dot.

`require()` is all you need to load other JS from your entry.

**Comment by 909oce** [comment]
i created /plugins/909 and put index.js within /909, however it doesnt run. im using the latest build. is this not implemented yet?

**Comment by nomi-san** [comment]
It works correctly in the latest build.
But there is a bug that not show where of error in your plugin.
