### ISSUE TITLE
ES modules & async plugins

### ISSUE THREAD

**Issue by nomi-san** [nomi-san/league-loader#35]
After `//plugins/` domain is supported, all entry plugins will be loaded asynchronously using native `import`.
But that doesn't mean `require` will be removed, because too many plugins are now using it.

When loading a plugin with `require`,  the root plugin will push to the path stack its absolute path. Then sub modules will know their path even they are required by relative path. In current implementation, only a static path stack is used, so there is **a bug that occurs when loading modules asynchronously**.

https://github.com/nomi-san/league-loader/blob/39fb814ca2b86c3b435c294c5dcc59f001d2b958/d3d9/src/renderer/ext_code.h#L103-L107

To keep legacy `require` and `import` working together, the `require` must be known its path. In ES module, `import.meta` is all we need to get the path, but we cannot use it inside `require` due to syntax error. Here is a possible way that patches plugin code before it  loads.

```diff
-const mod = require('./my-mod');
+const mod = require('./my-mod', import.meta);
```

Finally, web browser runtime doesn't allow to import module without file extension .js. In VSCode, the autocompletion always uses Node import type, now that is solved by 39fb814.

```js
import './a'   // => ./a.js
import './a/'  // => ./a/index.js
```

**Comment by douugdev** [comment]
Isn't it better to just support `commonjs` and leave to the developer to transpile it down from `ES6` and above to `commonjs` via babel or other transpiler?

**Comment by nomi-san** [comment]
I'm trying to keep the old plugins workable after switching to ESM.
Actually, many plugin developers are not using any front-end tooling/bundler and they dont have much experience with front-end webdev 😥

**Comment by douugdev** [comment]
That's my thinking too, and from what I understand the new update requires you to change how we need to call `require` (thus breaking any attempt to use bundlers and transpilers) and IMO it would be better to keep it as it is, avoid supporting ESM but add (such as my idea in #36) a bundler/transpiler boilerplate command, or by shipping with the release, such as a `webpack.config.js`, a `.babelrc`, `package.json` and a `_index.js` to something like `/plugins/my-project/`, so it transpiles to `/plugins/my-project/dist/index.js`

**Comment by douugdev** [comment]
![image](https://user-images.githubusercontent.com/59324692/218310007-95555a50-4c1f-4d42-aceb-3a4b42a3c351.png)

I've already built that dev environment and the DX is very pleasant, I'm able to use TypeScript, JSX and preact to create portals and render components everywhere in the client, use eslint and prettier to ensure best practices, SASS and SCSS modules for styling, axios for requests, etc. Just like developing a `create-react-app`, `vite` or `nextjs` application. The only difference from what i proposed is that my source folder is outside the plugins one, so i can name .js files without the underscore but still bundle everything to a single file inside.

![image](https://user-images.githubusercontent.com/59324692/218310262-99a1f4d4-2b6f-4248-bf85-0b5b02a9f64b.png)
