### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by douugdev** [nomi-san/league-loader#36]
Hey! Just started developing some plugins with this tool, so firstly I wanna say what an awesome tool it is, thank you @nomi-san for the awesome work, but there's definitely something I feel is missing, some kind of hot reload for CSS and/or JS.

See, for CSS I have found the following code reloads it:
```js

function reloadCSS() {
  const links = document.getElementsByTagName('link');

  Array.from(links)
    .filter(link => link.rel.toLowerCase() === 'stylesheet' && link.href)
    .forEach(link => {
      const url = new URL(link.href, location.href);
      url.searchParams.set('forceReload', Date.now());
      link.href = url.href;
    });
}
```

So maybe it's possible to do the same thing with JS plugins? For all I know you inject a `require` call in the CEF renderer, to require the plugins, maybe you could require a JS file to inject <link> tags that executes the plugins, then use the same CSS reload approach but calling a plugin with 
```html
<script src="https://plugins/plugin.js?forceReload=123820149801" />
```

**Comment by nomi-san** [comment]
Thanks.

In C++, watching file changes for hot reload is painful in main module, and I dont want it to get any bigger.

Just thought about using **Vite**,  it relates to #35. With Vite HMR, just inject its code into the client, every headache will be solved. For example with vanilla JS Vite exmaple:
```html
<!-- source -->
<script type="module" src="./main.js"></script>

<!-- transpiled -->
<script type="module" src="/@vite/client"></script>
<script type="module" src="/main.js"></script>
```

Then we will need a plugin development mode to support that with ease.

**Comment by douugdev** [comment]
I agree, I don't think you should implement file watching in C++ since there are a lot of JS tools for that out there, I am currently using webpack and though it hot-reloads, it doesn't update the script in the client.

I will look into Vite though, if it works with HMR, maybe it would be interesting to implement a boilerplate project so people can use it like CRA (e.g. `npx create-league-loader-plugin --template vite`
