### ISSUE TITLE
Support for wine

### ISSUE THREAD

**Issue by thanhdoan1201** [nomi-san/league-loader#5]
i use linux and run game on wine
software not work
![image](https://user-images.githubusercontent.com/109785213/211181688-26be9863-ad3e-4c7b-9db2-576815169bf3.png)

**Comment by nomi-san** [comment]
I have not tested on Wine.
Let's put all files of this tool to the LeagueClient.exe folder and restart the client.

**Comment by thanhdoan1201** [comment]
it not work

**Comment by thanhdoan1201** [comment]
it not work

**Comment by nomi-san** [comment]
Make sure it's running as admin.

You can put only d3d9.dll file and plugins folder to League's folder,
then start the client without activating League Loader.

**Comment by thanhdoan1201** [comment]
wine always running app as admin

**Comment by thanhdoan1201** [comment]
![image](https://user-images.githubusercontent.com/109785213/211185822-6eff3b14-e925-4917-9f8c-1778ffc54496.png)
OK

**Comment by thanhdoan1201** [comment]
but when i  press F12, client reload

**Comment by nomi-san** [comment]
You have to re-check the league-loader.js in plugin folders, or other plugins have set this hotkey.

https://github.com/nomi-san/league-loader/blob/1f9081407c780b632c8528510b38ebcc6de4edb8/bin/plugins/league-loader.js#L72-L79

**Comment by thanhdoan1201** [comment]
ah no, all link of tool when press -> reload client

**Comment by thanhdoan1201** [comment]
devtools not work bro

**Comment by nomi-san** [comment]
You can try remote DevTools:

1. Create config.cfg in League's folder
  ```ini
  [Main]
  RemoteDebuggingPort=8888
  ```
2. Open `http://localhost:8888/json` in your web browser.
3. Access the links are shown.

**Comment by thanhdoan1201** [comment]
![image](https://user-images.githubusercontent.com/109785213/211189866-8717f64b-e6f1-4295-9ff3-0d0e33ed6188.png)
OK

**Comment by thanhdoan1201** [comment]
nên list link dẫn đến devtools của từng trang trong list json khi vào trang localhost:8888/ 
cho nhanh

**Comment by thanhdoan1201** [comment]
cứ phải copy r ném lên thanh địa chỉ tốn time

**Comment by nomi-san** [comment]
> cứ phải copy r ném lên thanh địa chỉ tốn time

Trong tool có hyperlink **[Remote DevTools]** đấy bạn.
Phần hướng dẫn trên kia chỉ áp dụng cho trường hợp không dùng giao diện tool thôi.

**Comment by thanhdoan1201** [comment]
wine t báo lỗi khi nhấn **[Remote DevTools]**

**Comment by GeorgeV220** [comment]
so I wanted to run the latest version on wine but after some time (I have mono installed) I got this error:
https://pastebin.com/ZZGdGxpF

I not familiar with windows stacktraces. If you can help it would be awesome!!

**Comment by nomi-san** [comment]
The loader UI is built for .NET framework 4.5, maybe incompatible with MONO.
You can put the core.dll into LeagueClient folder and rename it to "d3d9.dll" or "version.dll"
then launch the client normally.
